[tool.poetry]
name = "pb-buddy"
version = "0.1.0"
description = "A package to help you ride better."
authors = ["Dustin Andrews"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.8.12"
numpy = "^1.21.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
