name: Complete Scrape

on:
 schedule:
   - cron: "23 7 * * 0"
 workflow_dispatch:
    inputs:
      num_jobs:
        description: "How many cores to use in building link list"
        required: true
        default: '4'
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: self-hosted2
    timeout-minutes: 1000
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install package
        shell: bash -l {0}
        run : |
          pip install poetry
          poetry install
      - name: Set env vars
        run: |
          echo "DATE=$(python -c 'import datetime as dt; print((dt.datetime.now()))')" >> $GITHUB_ENV
      - name: Log env
        run: env
      - name: Run Scraper
        shell: bash -l {0}
        run: python3 -m poetry run python scripts/scrape_base.py --num_jobs=${{github.event.inputs.num_jobs}}
        env: 
          COSMOS_CONN_STR : ${{secrets.COSMOS_CONN_STR}}
