name: Email Alerts

on:
  workflow_call:
    secrets:
      TWILIO_USER:
        required: true
      TWILIO_PASS:
        required: true

jobs:
  email-alerts:
    runs-on: self-hosted
    timeout-minutes: 1000
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install package
        run: |
          pip install poetry
          poetry install
      - name: Set env vars
        run: |
          echo "DATE=$(python -c 'import datetime as dt; print((dt.datetime.now()))')" >> $GITHUB_ENV
      - name: Log env
        run: env
      - name: Email alerts
        run: python3 -m poetry run python scripts/email_alerts.py
        env: 
          TWILIO_USER: ${{ secrets.TWILIO_USER }}
          TWILIO_PASS: ${{ secrets.TWILIO_PASS }}