name: Status Report

on:
  schedule:
    - cron: "23 23 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    concurrency:
      group: scrape
      cancel-in-progress: true
    runs-on: self-hosted
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install package
        run : |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry
          python3 -m poetry install
      - name: Set env vars
        run: |
          echo "DATE=$(python -c 'import datetime as dt; print((dt.datetime.now()))')" >> $GITHUB_ENV
      - name: Log env
        run: env
      - name: Run Scrape Report
        run: |
          make scrape_report
        env:
          COSMOS_CONN_STR : ${{secrets.COSMOS_CONN_STR}}
      - name: Email Scrape Report
        run: |
          poetry run python scripts/email_status_report.py
        env: 
          TWILIO_USER: ${{secrets.TWILIO_USER}}
          TWILIO_PASS: ${{secrets.TWILIO_PASS}}
          HOTMAIL_ADDRESS: ${{secrets.HOTMAIL_ADDRESS}}
          ADMIN_EMAIL: ${{secrets.ADMIN_EMAIL}}

