name: Scrape

on:
  schedule:
    - cron: "23 */2 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    concurrency:
      group: scrape
      cancel-in-progress: false
    runs-on: [self-hosted, self-hosted-testing]
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v9
        with:
          default: 3.8
          command: |
            pip install -U pip  # upgrade pip after installing python
            pip install poetry

      # - name: Set up Python 3.8
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.8
      - name: Install package
        run : |
          pyenv global 3.8
          poetry install
      - name: Set env vars
        run: |
          echo "DATE=$(python -c 'import datetime as dt; print((dt.datetime.now()))')" >> $GITHUB_ENV
      - name: Log env
        run: env
      - name: Run Scraper
        shell: bash -l {0}
        run: python3 -m poetry run python scripts/scrape_base.py
        env: 
          COSMOS_CONN_STR : ${{secrets.COSMOS_CONN_STR}}
  email-alerts:
      concurrency:
        group: scrape
        cancel-in-progress: false
      runs-on: [self-hosted, self-hosted-testing]
      steps:
        - name: Setup repo
          uses: actions/checkout@v2
        - name: Install python version
          uses: gabrielfalcao/pyenv-action@v9
          with:
            default: 3.8
            command: |
              pip install -U pip  # upgrade pip after installing python
              pip install poetry

        # - name: Set up Python 3.8
        #   uses: actions/setup-python@v2
        #   with:
        #     python-version: 3.8
        - name: Install package
          run : |
            pyenv global 3.8
            poetry install
        - name: Set env vars
          run: |
            echo "DATE=$(python -c 'import datetime as dt; print((dt.datetime.now()))')" >> $GITHUB_ENV
        - name: Log env
          run: env
        - name: Email alerts
          shell: bash -l {0}
          run: python3 -m poetry run python scripts/email_alerts.py
          env: 
            TWILIO_USER: ${{secrets.TWILIO_USER}}
            TWILIO_PASS: ${{secrets.TWILIO_PASS}}
            HOTMAIL_ADDRESS: ${{secrets.HOTMAIL_ADDRESS}}
            COSMOS_CONN_STR : ${{secrets.COSMOS_CONN_STR}}
        - name: Commit files
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"        
            git add logs/
            git add alerts/
            git commit -m "Add data for $DATE"
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}

