name: Scrape

on:
  schedule:
    - cron: "23 */1 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: self-hosted
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install package
        run : |
          python3 -m pip install --upgrade pip
          python3 -m pip install poetry
          python3 -m poetry install
      - name: Set env vars
        run: |
          echo "DATE=$(python -c 'import datetime as dt; print((dt.datetime.now()))')" >> $GITHUB_ENV
      - name: Log env
        run: env
      - name: Run Scraper
        shell: bash -l {0}
        run: python3 -m poetry run python scrape_base.py
        env: 
          COSMOS_CONN_STR : ${{secrets.COSMOS_CONN_STR}}
      - name: Email alerts
        shell: bash -l {0}
        run: python3 -m poetry run python email_alerts.py
        env: 
          TWILIO_USER: ${{secrets.TWILIO_USER}}
          TWILIO_PASS: ${{secrets.TWILIO_PASS}}
          HOTMAIL_ADDRESS: ${{secrets.HOTMAIL_ADDRESS}}
          COSMOS_CONN_STR : ${{secrets.COSMOS_CONN_STR}}
      # Pull prior work to make sure we commit after recent work. Keep logs, alerts from current process in merge
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"        
          git add logs/
          git add alerts/
          git commit -m "Add data for $DATE"
#          git pull
#          git checkout --ours logs/
#          git add logs/
#          git checkout --ours alerts/
#          git add alerts/
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
