name: Scrape

on:
  schedule:
    - cron: "23 8 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pb-buddy
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - name: Set env vars
        run: |
          echo "DATE=$(python -c 'import datetime as dt; print((dt.datetime.now()).date())')" >> $GITHUB_ENV
      - name: Log env
        run: env
      - name: Run Scraper
        run: python scrape_base.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"        
          git add data/
          git add logs/
          git commit -m "Add data for $DATE"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}