name: Scrape North America
concurrency: ${{ github.workflow }}

on:
 schedule:
   - cron: "23 */5 * * 1-6"
 workflow_dispatch:
    inputs:
      num_jobs:
        description: "How many cores to use in building link list"
        required: true
        default: '4'
jobs:
  scrape-na:
    uses: ./.github/workflows/scrape_template.yml
    with:
      num_jobs: ${{ github.event.inputs.num_jobs }}
      region: '3'
    secrets:
      COSMOS_CONN_STR: ${{ secrets.COSMOS_CONN_STR }}
  email-alerts:
    needs: scrape-na
    uses: ./.github/workflows/email_template.yml
    secrets:
      TWILIO_USER: ${{ secrets.TWILIO_USER }}
      TWILIO_PASS: ${{ secrets.TWILIO_PASS }}
      COSMOS_CONN_STR: ${{ secrets.COSMOS_CONN_STR }}
      HOTMAIL_ADDRESS: ${{ secrets.HOTMAIL_ADDRESS }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
